import MainHeader from '@/src/components/MainHeader/MainHeader'
import './globals.css'
import type { Metadata } from 'next'
import { Barlow, Inter } from 'next/font/google'
import { Lato } from 'next/font/google'
import { Cabin } from 'next/font/google'
import { Abel } from 'next/font/google'
import { ApolloWrapper } from '@/lib/apollo-wrapper'

import NextAuthProvider from './context/Provider'
import GlobalPlayer from '../components/Media/GlobalPlayer'
import GlobalAudio from '../components/Media/GlobalAudio/GlobalAudio'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })
const lato = Lato({ weight: '700', subsets: ['latin'] })
const cabin = Cabin({ subsets: ['latin'] })
const abel = Abel({ weight: '400', subsets: ['latin'] })
const barlow = Barlow({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BFK Music',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  console.log({ children })

  return (
    <html lang="en">
      <body className={` ${barlow.className}`}>
        <NextAuthProvider>
          <ApolloWrapper>
            <MainHeader />
            <div className=" flex justify-center">{children}</div>
            <GlobalPlayer />
            <GlobalAudio />
          </ApolloWrapper>
        </NextAuthProvider>
      </body>
    </html>
  )
}
